#!/bin/bash
set -e;

APP="$1"

REDIS_APP_IMAGE="redis/$APP"

# Check if an existing volume exists
REDIS_APP_IMAGE_ID=$(docker images | grep "$REDIS_APP_IMAGE" |  awk '{print $3}')
if [[ -n $REDIS_APP_IMAGE_ID ]]; then
    echo    "-----> Checking status of Redis"

    # Check if Redis container is installed
    REDIS_IMAGE=$(docker images | grep "dokkuinstaller/redis " |  awk '{print $3}')
    if [[ -z $REDIS_IMAGE ]]; then
        echo "Redis image not found... Did you run 'dokku plugins-install' ?"
        exit 1
    fi

    echo    "       Found image redis/$APP volume"
    echo -n "       Checking status... "

    REDIS_APP_CONTAINER_ID=$(docker ps | grep "$REDIS_APP_IMAGE" |  awk '{print $1}')
    if [[ -n $REDIS_APP_CONTAINER_ID ]]; then
        echo "ok."
    else
        echo "stopped."
	HOST_DIR="$DOKKU_ROOT/.redis/volume-$APP"
	if [[ -d $HOST_DIR ]]; then
		echo
		echo "-----> Reusing redis/$APP database"
	else
		mkdir -p $HOST_DIR
	fi
	REDIS_VOLUME="$HOST_DIR:/var/lib/redis"

        echo -n "       Launching $REDIS_APP_IMAGE... "
        echo "COMMAND: docker run -v $REDIS_VOLUME -p 6379 -d $REDIS_APP_IMAGE /bin/start_redis.sh"

	ID=$(docker run -v $REDIS_VOLUME -p 6379 -d $REDIS_APP_IMAGE /bin/start_redis.sh)
        sleep 1

	dokku redis:link $APP $APP
	echo "ok."
    fi
fi
