#!/bin/bash

# Build docker image
git clone https://github.com/brianpattison/dokku-pg-dockerfiles /tmp/dokku-pg-dockerfiles
docker build -q=true -t brianpattison/postgresql /tmp/dokku-pg-dockerfiles
rm -rf /tmp/dokku-pg-dockerfiles

# Install postgresql-client
RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main" > /etc/apt/sources.list.d/pgdg.list
RUN wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
RUN apt-get update
apt-get install -y postgresql-client-9.4
