#!/bin/bash

# Pull Postgres Images
docker pull dokkuinstaller/postgres:9.3
docker pull dokkuinstaller/postgres:9.4
docker pull dokkuinstaller/postgres:latest

# Install postgres-client
apt-get install -y postgresql-client
