#!/bin/bash
set -e;

echo "IS POSTGRES PREDEPLOY BEING HIT????"

APP="$1"

PG_APP_IMAGE="postgres/$APP"

echo "PG_APP_IMAGE: $PG_APP_IMAGE"

# Check if an existing DB volume exists
PG_APP_IMAGE_ID=$(docker images | grep "$PG_APP_IMAGE" |  awk '{print $3}')
echo "PG_APP_IMAGE_ID: $PG_APP_IMAGE_ID"
if [[ -n $PG_APP_IMAGE_ID ]]; then
    echo    "-----> Checking status of PostgreSQL"

    # Check if DB container is installed
    PG_IMAGE=$(docker images | grep "dokkuinstaller/postgres " |  awk '{print $3}')
	echo "PG_IMAGE: $PG_IMAGE"
    if [[ -z $PG_IMAGE ]]; then
        echo "PostgreSQL image not found... Did you run 'dokku plugins-install' ?"
        exit 1
    fi

    echo    "       Found image postgres/$APP database"
    echo -n "       Checking status... "

    PG_APP_CONTAINER_ID=$(docker ps | grep "$PG_APP_IMAGE" |  awk '{print $1}')
	echo "PG_APP_CONTAINER_ID: $PG_APP_CONTAINER_ID"
    if [[ -n $PG_APP_CONTAINER_ID ]]; then
        echo "ok."
    else
        echo "stopped."
		DB_PASSWORD=$(cat "$DOKKU_ROOT/.postgres/pwd_$APP")
        PG_VOLUME="$DOKKU_ROOT/.postgres/volume_$APP:/opt/postgresql"

        echo -n "       Launching $PG_APP_IMAGE... "
        echo "COMMAND: docker run -v $PG_VOLUME -p 5432 -d $PG_APP_IMAGE /usr/bin/start_pgsql.sh $DB_PASSWORD"

		ID=$(docker run -v $PG_VOLUME -p 5432 -d $PG_APP_IMAGE /usr/bin/start_pgsql.sh $DB_PASSWORD)
        sleep 1

		PORT=$(docker port "$ID" 5432 | sed 's/0.0.0.0://')
		dokku config:set $APP "DATABASE_URL=postgres://root:$DB_PASSWORD@172.17.42.1:$PORT/db"

		echo "ok."
    fi
fi
